# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
        dotnet build
    - name: Build
      run: |
        cd src
        dotnet tool restore
        dotnet r pack


    - name: 'Upload nuget'
      uses: actions/upload-artifact@v2
      with:
        name: Nuget_${{github.run_number}}
        path: src/PACK
        retention-days: 1
  
    - name: push to nuget
      if: startsWith(github.ref, 'refs/tags/v') # This line ensures the step runs only if a tag version is present
      run: |
        dir src/PACK/*.*
        echo '1'
        dir src/PACK/*.symbols.nupkg  
        echo '2'
        dotnet nuget push src\PACK\*.symbols.nupkg --api-key  ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
  
    
